spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management_system_Backend?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create